site_name: "HEIMDALL Wiki"
site_description: "A guide to building your own Low-Cost Liquid Handler"

theme:
  name: material
  palette:
    # This sets up a toggle for light and dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs      # Top navigation bar
    - navigation.indexes   # Allows folders to have their own landing pages
    - search.suggest       # Smart search bar dropdowns

# This defines the sidebar structure of your wiki
nav:
  - Home: index.md
  - Getting Started: setup.md
  - Hardware: hardware.md
  - Software: software.md
  - GUI: user_interface.md

markdown_extensions:
  - admonition
  - pymdownx.details
